const mockDeals = [
  {
    id: 1,
    destination: "Santorini, Greece",
    origin: "Berlin, DE",
    price: 450,
    originalPrice: 780,
    savings: "42%",
    hotel: "Canaves Oia Luxury Suites",
    rating: 4.9,
    reviews: 1240,
    prediction: "Price likely to increase in 48h",
    tags: ["Hot", "Smart Combo"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=800",
    seasonality: "Peak Season",
    distanceToSea: "0.2 km (Cliffside)",
    mountains: "N/A",
    aiInsight: "Reviews highlight 'exceptional sunset views' and 'private infinity pools'. Quiet location away from the main Fira crowds."
  },
  {
    id: 2,
    destination: "Madeira, Portugal",
    origin: "Warsaw, PL",
    price: 320,
    originalPrice: 550,
    savings: "41%",
    hotel: "Belmond Reid's Palace",
    rating: 4.7,
    reviews: 850,
    prediction: "Price stable",
    tags: ["Smart Combo"],
    image: "https://images.unsplash.com/photo-1551041777-ed9383fd3818?auto=format&fit=crop&q=80&w=800",
    seasonality: "High Season",
    distanceToSea: "0.5 km",
    mountains: "Hiking trails within 2km",
    aiInsight: "Historical luxury. Sentiment analysis shows high satisfaction with the 'botanical gardens' and 'afternoon tea service'."
  },
  {
    id: 3,
    destination: "Tenerife, Spain",
    origin: "Paris, FR",
    price: 280,
    originalPrice: 420,
    savings: "33%",
    hotel: "The Ritz-Carlton, Abama",
    rating: 4.8,
    reviews: 2100,
    prediction: "Dropping soon (70% probability)",
    tags: ["Flash Deal"],
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&q=80&w=800",
    seasonality: "All-year",
    distanceToSea: "Frontline Beach",
    mountains: "Teide views from most rooms",
    aiInsight: "Families love the 'isolated beach access'. AI detected a potential price drop due to recent low-occupancy signals."
  }
];
